version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "12:00"
      timezone: "Europe/Zurich"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "12:00"
      timezone: "Europe/Zurich"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    ignore:
      # Our apps are not yet ready for ember-data v5
      - dependency-name: ember-data
        versions:
          - ">= 5"
      # https://github.com/villander/ember-engines-router-service/issues/67
      - dependency-name: ember-engines-router-service
        versions:
          - ">= 0.4.0 <= 4.4.1"
